### ISSUE TITLE
Unable to build the src/Horizon.elm

### ISSUE THREAD

**Issue by kraklin** [abadi199/elm-horizon#1]
Hi,

I wanted to play a little bit with Horizon and Elm and stumble upon your library. I cloned the repo and run npm start, but the elm-live gave me the compiler error. So I try to compile it with elm-make and I've got the same error:

`bash-3.2$ elm-make src/Horizon.elm  
-- DOCUMENTATION ERROR ----------------------------------------- src/Horizon.elm       

You must have a documentation comment between the module declaration and the  
imports.                                                                               

26| import Json.Decode as Json exposing (Decoder)  
    ^  
Learn more at http://package.elm-lang.org/help/documentation-format  
                                                                             `

I find out, that you need to have the documentation when you are exposing the functions. Am I doing something wrong or am I missing something?

Thanks

**Comment by abadi199** [comment]
It's my bad. I was experimenting with `elm-github-install` and forgot to revert the `elm-package.json`. Can you try again and let me know if my latest commit fix this issue?

Thanks.

**Comment by kraklin** [comment]
Everything is working now :) Thanks, I\m going to play with it little bit now.
